### PR TITLE
Include the xml error response in verify_dynamics_login

### PR DESCRIPTION
**Pull request by bgschiller**
php support for https://trello.com/c/6d069qSs/1404-on-dynamics-login-error-pass-back-full-xml-error-message-to-frontend-display-on-frontend-hidden-by-a-button-display-full-error-m

### CODE REVIEW

**Comment by emeth-** [comment]
Nothing looks improper to me. What is the scope of the review you are requesting here? Did you want me to actively test this code?

**Comment by bgschiller** [comment]
@emeth- Nosir, I'm confident that this won't break anything. Just wanted to defer merging it to you, as I believe it gets pushed to prod immediately.

**Comment by emeth-** [comment]
@bgschiller Ah, I follow.

In that case, please split out your changes into a separate endpoint, that way we can push without concern.

**Comment by bgschiller** [comment]
@emeth- okay, no problem.

**Comment by bgschiller** [comment]
Once this is merged, we can send https://github.com/TopOPPS/topopps-web/pull/3331 to dev for testing.

**Comment by emeth-** [comment]
@bgschiller Thanks! Merged!

**Pull request merged**
